### ISSUE TITLE
change name

### ISSUE THREAD

**Issue by molikd** [FAIR-bioHeaders/FHR-File-Converter#6]
change name of organization to: FAIR bioHeaders
change name of Reference Genome Standard to FHR
change file extension to .fh.~whatever~

**Comment by molikd** [comment]
@adamjohnwright 

This sound right?

**Comment by adamjohnwright** [comment]
Yes, that sounds great to me. Also, the GitHub name that appears in the URL should be something like "FairBioHeaders". 

FHR sounds good to me. 

the file extension should in general be .fh.<filetype>. That being said I think for the reference genome FASTA it should be .fhr.[fa|fasta]. This opens the door to making file headers for other sequences that are stored in FASTA file format. 

Does that sound right to you @molikd?

**Comment by molikd** [comment]
converted.
